### ISSUE TITLE
RGB only?

### ISSUE THREAD

**Issue by OliverEvans96** [mpizenberg/computer-vision-rs#9]
Hello,

This looks like a great project! I'm not very familiar with VO / CV in general. It seems that a depth map is necessary for each frame.

Is it possible to use this library without depth maps? If not, can you suggest a way to calculate/approximate them?

My goal is simply to determine the motion of a camera through a static environment given a set of RGB images.

Thanks!
Oliver

**Comment by mpizenberg** [comment]
Hi @OliverEvans96 thanks for the kind words. Eventually the goals were to reach that point where only RGB images are needed indeed. I didn’t get the time to complete this project to that point. One way would be to initialize depth maps with disparity search, as is done in stereo vision. Another way is to retrieve an approximate depth map using deep learning. But in all cases, this project isn’t as advanced and robust as state of the art projects.
I could recommend ORB-SLAM, which was the best last time I checked, https://github.com/UZ-SLAMLab/ORB_SLAM3

**Comment by mpizenberg** [comment]
Otherwise, if you’re interested in a more deep dive in the subject (never knows ^^) I could recommend the parts of my thesis explaining this project. You can find the pdf and the defense video from this page https://matthieu.pizenberg.fr/research/thesis/

**Comment by OliverEvans96** [comment]
Thanks a lot for the reply!
